### ISSUE TITLE
Does not work on Ubuntu

### ISSUE THREAD

**Issue by alxpsr** [Jack89ita/vscode-copy-filename#14]
```
OS: Ubuntu 18.04
VSCode: 1.43.1
```
I tried to copy from context menu and does nothing happen :(

Errors stack from devTools:
```
console.ts:137 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/usr/share/code/resources/app/out/bootstrap.js:5:80)	at process.emit (events.js:203:13)

mainThreadExtensionService.ts:66 Error: write EPIPE
	at afterWriteDispatched (internal/stream_base_commons.js:146)
	at writeGeneric (internal/stream_base_commons.js:137)
	at Socket._writeGeneric (net.js:698)
	at Socket._write (net.js:710)
	at doWrite (_stream_writable.js:418)
	at writeOrBuffer (_stream_writable.js:402)
	at Socket.Writable.write (_stream_writable.js:302)
	at Socket.Writable.end (_stream_writable.js:583)
	at Socket.end (net.js:536)
	at handleInput (/home/alxpsr/.vscode/extensions/jack89ita.copy-filename-2.3.1/node_modules/execa/index.js:75)
	at module.exports (/home/alxpsr/.vscode/extensions/jack89ita.copy-filename-2.3.1/node_modules/execa/index.js:273)
	at /home/alxpsr/.vscode/extensions/jack89ita.copy-filename-2.3.1/node_modules/clipboardy/lib/linux.js:18
	at processTicksAndRejections (internal/process/task_queues.js:85)
```

**Comment by alxpsr** [comment]
Any update?

**Comment by kyrenia** [comment]
Also experiencing the same issue with Ubuntu 20.04 and VSCode 1.46.0-insider

**Comment by Jack89ita** [comment]
Hello @kyrenia and @alxpsr ,
Sorry for the late response; i've updated the extension and tested with Ubuntu 18 / VSCode 1.43 and it is working for me.
Can you try it out and let me know?
Thank you very much!

**Comment by kyrenia** [comment]
Hi - I am still experiencing the same issue with 2.3.2 (running on Ubuntu 20.04 and VSCode 1.46.0-insider)

**Comment by Jack89ita** [comment]
Hello @kyrenia,
does the extension print some kind of error?

**Comment by kyrenia** [comment]
Nothing is printed on the location of paste. Below is details of error. 


``4console.ts:137 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/usr/share/code-insiders/resources/app/out/bootstrap.js:5:80)	at process.emit (events.js:203:13) (at process.<anonymous> (/usr/share/code-insiders/resources/app/out/bootstrap.js:5:74))
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Both xsel and fallback failed (at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:970:146)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] stack trace: Error: Both xsel and fallback failed	at makeError (/home/username/.vscode-insiders/extensions/jack89ita.copy-filename-2.3.2/node_modules/clipboardy/lib/linux.js:16:11)	at xselWithFallback (/home/username/.vscode-insiders/extensions/jack89ita.copy-filename-2.3.2/node_modules/clipboardy/lib/linux.js:31:10)	at processTicksAndRejections (internal/process/task_queues.js:85:5) (at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:970:225)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:65 [[object Object]]Both xsel and fallback failed
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:66 Error: Both xsel and fallback failed
	at makeError (/home/username/.vscode-insiders/extensions/jack89ita.copy-filename-2.3.2/node_modules/clipboardy/lib/linux.js:16)
	at xselWithFallback (/home/username/.vscode-insiders/extensions/jack89ita.copy-filename-2.3.2/node_modules/clipboardy/lib/linux.js:31)
	at processTicksAndRejections (internal/process/task_queues.js:85)

**Comment by Jack89ita** [comment]
I can reproduce the issue now.
I've opened an issue in the clipboardy repository [here](https://github.com/sindresorhus/clipboardy/issues/66).
Let's see if someone can help us.
Thanks!

**Comment by kyrenia** [comment]
thank you for looking into! The lack of being able to copy filename is the key feature that I miss having transitioned from Notepad++ (when I switched to Linux and needed a editor)

**Comment by alxpsr** [comment]
@Jack89ita hi there! 
Output: http://i.imgur.com/pyciaug.png

Sorry, i can't use your app anymore :(
Anyway, thank's a lot for response and support

**Comment by alxpsr** [comment]
If you need, i can help you for reproduce this bug

**Comment by Robula** [comment]
Doesn't work on Windows with WSL either.

**Comment by standard-software** [comment]
vscode.env.clipboard.writeText(text);
If you use this method, it will work on wsl ubuntu as well.

not good
- require('clipboardy');
- require('copy-paste');


vscode-insert-line-number-and-copy/extension.js at main · standard-software/vscode-insert-line-number-and-copy
https://github.com/standard-software/vscode-insert-line-number-and-copy/blob/main/src/extension.js

**Comment by OnkelTem** [comment]
Doesn't work on Kubuntu 20.04. 
Meh... this is the only function of this extension, please.

**Comment by Jack89ita** [comment]
@OnkelTem this repo is not supported anymore. You can write your one without being so rude.

**Comment by OnkelTem** [comment]
Nobody being rude.
Why keeping this extension published then?

**Comment by Jack89ita** [comment]
@OnkelTem Maybe for those who are not using Ubuntu? By the way you can fix any problem you have submitting a pull request...

**Comment by standard-software** [comment]
Wouldn't it be better to use this one?
Maybe the usability is different.

Copy filename - Visual Studio Marketplace
https://marketplace.visualstudio.com/items?itemName=bradzacher.vscode-copy-filename

In that extension
  vscode.env.clipboard.writeText(accumulator).then(
The code is as follows.

vscode-copy-filename/extension.ts at main - bradzacher/vscode-copy-filename
https://github.com/bradzacher/vscode-copy-filename/blob/main/src/extension.ts#L72
