### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bigfoot31** [Jack89ita/vscode-copy-filename#3]
Not working at all.

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-20-generic

**Comment by Jack89ita** [comment]
Hello @bigfoot31, thank you for the feedback. 
Can you please tell me what are you trying to achive and how? So i can have a better idea how to fix it.
Thanks!

**Comment by cxwithyxy** [comment]
Not working too !

OS: Windows 10 17134

**Comment by alxpsr** [comment]
Same problem
OS: `Win10_x64`
VSCode: `1.33.1`
Extension version: `2.1.1`

### Error stack from dev-tools
```
[Extension Host] Activating extension `jack89ita.copy-filename` failed:  Cannot find module 'clipboardy'
t.log @ console.ts:134
console.ts:134 [Extension Host] Here is the error stack:  Error: Cannot find module 'clipboardy'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\aperevalov\.vscode\extensions\jack89ita.copy-filename-2.1.1\extension.js:3:20)
	at Object.<anonymous> (C:\Users\aperevalov\.vscode\extensions\jack89ita.copy-filename-2.1.1\extension.js:28:3)
	at Module.t._initNodeRequire.r._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:31:542)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:717:918
	at E._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:718:2)
	at E._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:716:772)
	at E.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:714:224)
	at Generator.next (<anonymous>)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:11:176)
	at new Promise (<anonymous>)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:975)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:713:946)
	at p._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:765)
	at define._activateExtensions.i.length.Promise.all.o.map.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:449)
	at Array.map (<anonymous>)
	at p._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:437)
	at p.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:455:375)
	at E._activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:715:434)
	at define.$activateByEvent._readyToRunExtensions.wait.then.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:723:359)
```

**Comment by parthi2929** [comment]
Not working for me as well.   Right clicking the file name and selecting your option does not get the file name to clip board at all.  It was working fine earlier. I think with recent vs code update, it is failing. 

Version: 1.33.1 (user setup)
OS: Windows_NT x64 10.0.17134

**Comment by Jack89ita** [comment]
Hi guys, sorry for the late response,
I've just updated the plugin, can you try it and see if it works?
Thank you!

**Comment by alxpsr** [comment]
@Jack89ita Worked with `2.1.2`. Thank you

**Comment by Jack89ita** [comment]
Thank you @alxpsr, glad it worked! I will wait a few days to see if other users still have the issue, otherwise i will close the thread.

**Comment by cxwithyxy** [comment]
@Jack89ita  IT WORKS !!! (✪ω✪)

**Comment by kaisuj** [comment]
Version 2.1.2 works fine on Win10 but does not on Linux 4.18.0-16 (Linux Mint based on Ubuntu 18.04). On both OS I use CopyQ clipboard manager but I'm not sure if this is an issue. No matter if I open context menu on file in explorer or on opened file tab, file name is not coppied.
